

name: GitActions Demo

on: [push]

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps: 
    - run: echo 'Hello World!'
    - run: echo 'Running on ${{runner.os}}' 
  
  exercise_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello World'
    - run: pwd
    - run: ls -a
    - run: echo 'Commit message ${{ github.event.head_commit.message }}'
    - run: echo 'job name ${{ github.job }}'
    
  clone_job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -a
    - name: Checkout
      uses: actions/checkout@v2.5.0 # Default repo to clone down / checkout is our one
    - run: echo '${{github.repository}}'
    - run: ls -a
    - run: cat file1.txt
    - run: echo "This is new text" >> file1.txt
    - run: cat file1.txt
    
  new_job1:
    runs-on: ubuntu-latest 
    steps:
    - run: touch Hello.py
    - run: cat Hello.py
    - run: echo "this is new" >> Hello.py 
    - run: cat Hello.py
